# Generated by Django 4.0.4 on 2022-04-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='CNPJ')),
                ('business_name', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('title_establishment', models.CharField(max_length=50, verbose_name='Fantasia')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['business_name'],
            },
        ),
    ]
