# Generated by Django 4.0.4 on 2022-05-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores_images/', verbose_name='Logotipo'),
        ),
    ]
