# Generated by Django 4.0.4 on 2022-04-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
    ]
