# Generated by Django 4.0.4 on 2022-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_stores_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stores',
            name='logo',
        ),
        migrations.AddField(
            model_name='stores',
            name='group',
            field=models.CharField(choices=[('Doceria', 'Doceria'), ('Vestuário', 'Vestuário'), ('Pizzaria', 'Pizzaria'), ('Restaurante', 'Restaurante'), ('Lanchonete', 'Lanchonete')], default='Lanchonete', max_length=15, verbose_name='Grupo'),
            preserve_default=False,
        ),
    ]
