# Generated by Django 4.0.4 on 2022-05-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_stores_logo_stores_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='group',
            field=models.CharField(choices=[('Doceria', 'Doceria'), ('Lanchonete', 'Lanchonete'), ('Pizzaria', 'Pizzaria'), ('Restaurante', 'Restaurante'), ('Vestuário', 'Vestuário')], max_length=15, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='title_establishment',
            field=models.CharField(max_length=27, verbose_name='Fantasia'),
        ),
    ]
