# Generated by Django 4.0.4 on 2022-05-22 09:51

from django.db import migrations, models
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_stores_title_establishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='cnpj',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, validators=[stores.models.Stores.validate_cnpj], verbose_name='CNPJ'),
        ),
    ]
