name: Digital-Showcase CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DJANGO_SECRET_KEY: 7x5e14nv-e)#qz_t+4e04p8$_2=_%45ko0*)nh*n!vs_lj@ea&

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.10.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install pip --upgrade
        pip install -r requirements.txt
    - name: Preparing file with environment variables
      run: |
        touch .env
    - name: Database preparation
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test
