# Generated by Django 4.0.4 on 2022-05-12 02:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('ean13code', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Código EAN-13')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('sale', models.BooleanField(default=False, verbose_name='Promoção')),
                ('discount', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Desconto')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('amount_stock', models.IntegerField(verbose_name='Qtde em Estoque')),
                ('discontinued', models.BooleanField(default=False, verbose_name='Descontinuado')),
                ('recorded', models.DateTimeField(auto_now_add=True, verbose_name='Gravado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('store_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.stores', verbose_name='Loja Detentora')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/', verbose_name='Imagem')),
                ('type', models.CharField(choices=[('Capa', 'Capa'), ('Adicional', 'Adicional')], max_length=9, verbose_name='Tipo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem de Produto',
                'verbose_name_plural': 'Imagens de Produto',
                'ordering': ['product'],
            },
        ),
    ]
